version: '3.9'
services:
  app:
    image: "pan1c/docker-netns-exporter:1.1.0"
    privileged: true
    volumes:
      - "/var/run/docker/netns:/var/run/docker/netns:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      CRON: "* * * * *"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
